[global]
num_runs = 1
site = strasbourg

# If this is a test of spatial use (impacts stats only)
spatial_comparison = False
# If want to create stats and plots for converged runs
rpl_convergence_comparison = False

[testbed]
# Duration in minutes
duration = 26

# Duration before applying stats to app packets (only used in stats)
app_warmup = 18

# Nodes utilized
#nodes = 69+67+65+63+61+58+56+54+52+49+46+44+42+40+38+36
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316+314+312+310+308
nodes = 35+4+5+8+10+11+14+25+42+39+51+64+61+60+58+55+54+47+30+19+31+50+33+22+1+37

[layered-p22]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m22dBm
makeflags = LAYERED=1
description = Layered-p22
group1 = Layered
group2 = m22dBm

#[minimal-p17]
#cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m17dBm -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
#description = 6TiSCH-minimal-p17
#group1 = Minimal
#group2 = m17dBm

#[orchestra-p17]
#cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m17dBm
#makeflags = ORCHESTRA=1
#description = Orchestra-p17
#group1 = Orchestra
#group2 = m17dBm


[layered-p17]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m17dBm
makeflags = LAYERED=1
description = Layered-p17
group1 = Layered
group2 = m17dBm


[layered-p12]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m12dBm
makeflags = LAYERED=1
description = Layered-p12
group1 = Layered
group2 = m12dBm


[layered-p7]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DRF2XX_TX_POWER=PHY_POWER_m7dBm
makeflags = LAYERED=1
description = Layered-p7
group1 = Layered
group2 = m7dBm

