[global]
num_runs = 7

# If this is a test of spatial use (impacts stats only)
spatial_comparison = False
# If want to create stats and plots for converged runs
rpl_convergence_comparison = False

[testbed]
# Duration in minutes
duration = 23

# Duration before applying stats to app packets (only used in stats)
app_warmup = 15

# Nodes utilized
#nodes = 69+67+65+63+61+58+56+54+52+49+46+44+42+40+38+36
nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316+314+312+310+308

[layered-8]
cflagsextra = -DSEND_CONF_INTERVAL=800
makeflags = LAYERED=1
description = Layered-8s
group1 = Layered
group2 = 8 s

[minimal-8]
cflagsextra = -DSEND_CONF_INTERVAL=800 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-8s
group1 = Minimal
group2 = 8 s

[orchestra-8]
cflagsextra = -DSEND_CONF_INTERVAL=800
makeflags = ORCHESTRA=1
description = Orchestra-8s
group1 = Orchestra
group2 = 8 s

[layered-4]
cflagsextra = -DSEND_CONF_INTERVAL=400
makeflags = LAYERED=1
description = Layered-4s
group1 = Layered
group2 = 4 s

[minimal-4]
cflagsextra = -DSEND_CONF_INTERVAL=400 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-4s
group1 = Minimal
group2 = 4 s

[orchestra-4]
cflagsextra = -DSEND_CONF_INTERVAL=400
makeflags = ORCHESTRA=1
description = Orchestra-4s
group1 = Orchestra
group2 = 4 s

[layered-2]
cflagsextra = -DSEND_CONF_INTERVAL=200
makeflags = LAYERED=1
description = Layered-2s
group1 = Layered
group2 = 2 s

[minimal-2]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-2s
group1 = Minimal
group2 = 2 s

[orchestra-2]
cflagsextra = -DSEND_CONF_INTERVAL=200
makeflags = ORCHESTRA=1
description = Orchestra-2s
group1 = Orchestra
group2 = 2 s

[layered-1]
cflagsextra = -DSEND_CONF_INTERVAL=100
makeflags = LAYERED=1
description = Layered-1s
group1 = Layered
group2 = 1 s

[minimal-1]
cflagsextra = -DSEND_CONF_INTERVAL=100 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-1s
group1 = Minimal
group2 = 1 s

[orchestra-1]
cflagsextra = -DSEND_CONF_INTERVAL=100
makeflags = ORCHESTRA=1
description = Orchestra-1s
group1 = Orchestra
group2 = 1 s

[layered-0-5]
cflagsextra = -DSEND_CONF_INTERVAL=50
makeflags = LAYERED=1
description = Layered-0.5s
group1 = Layered
group2 = 0.5 s

[minimal-0-5]
cflagsextra = -DSEND_CONF_INTERVAL=50 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-0.5s
group1 = Minimal
group2 = 0.5 s

[orchestra-0-5]
cflagsextra = -DSEND_CONF_INTERVAL=50
makeflags = ORCHESTRA=1
description = Orchestra-0.5s
group1 = Orchestra
group2 = 0.5 s
