[global]
num_runs = 14
cflagsextra = -DSEND_CONF_INTERVAL=200

# If this is a test of spatial use (impacts stats only)
spatial_comparison = False
# If want to create stats and plots for converged runs
rpl_convergence_comparison = False

[testbed]
# Duration in minutes
duration = 26

# Duration before applying stats to app packets (only used in stats)
app_warmup = 18

# Nodes utilized
#nodes = 69+67+65+63+61+58+56+54+52+49+46+44+42+40+38+36
nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316+314+312+310+308

[layered-n3]
cflagsextra = -DAPP_CONF_NUM_SOURCES=3
makeflags = LAYERED=1
description = Layered-n3
group1 = Layered
group2 = 3 nodes

[layered-n7]
cflagsextra = -DAPP_CONF_NUM_SOURCES=7
makeflags = LAYERED=1
description = Layered-n7
group1 = Layered
group2 = 7 nodes

#[layered-n11]
#cflagsextra = -DAPP_CONF_NUM_SOURCES=11
#makeflags = LAYERED=1
#description = Layered-n11
#group1 = Layered
#group2 = 11 nodes

[layered-n15]
cflagsextra = -DAPP_CONF_NUM_SOURCES=15
makeflags = LAYERED=1
description = Layered-n15
group1 = Layered
group2 = 15 nodes

