[global]
num_runs = 5

# If this is a test of spatial use (impacts stats only)
spatial_comparison = False
# If want to create stats and plots for converged runs
rpl_convergence_comparison = False

[testbed]
# Duration in minutes
duration = 26

# Duration before applying stats to app packets (only used in stats)
app_warmup = 18

# Nodes utilized
#nodes = 69+67+65+63+61+58+56+54+52+49+46+44+42+40+38+36
nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316+314+312+310+308

[layered-n6]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=6
makeflags = LAYERED=1
description = Layered-n6
group1 = Layered
group2 = 6 nodes

[minimal-n6]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=6 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-n6
group1 = Minimal
group2 = 6 nodes

[orchestra-n6]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=6
makeflags = ORCHESTRA=1
description = Orchestra-n6
group1 = Orchestra
group2 = 6 nodes


[layered-n9]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=9
makeflags = LAYERED=1
description = Layered-n9
group1 = Layered
group2 = 9 nodes

[minimal-n9]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=9 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-n9
group1 = Minimal
group2 = 9 nodes

[orchestra-n9]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=9
makeflags = ORCHESTRA=1
description = Orchestra-n9
group1 = Orchestra
group2 = 9 nodes


[layered-n12]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=12
makeflags = LAYERED=1
description = Layered-n12
group1 = Layered
group2 = 12 nodes

[minimal-n12]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=12 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-n12
group1 = Minimal
group2 = 12 nodes

[orchestra-n12]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=12
makeflags = ORCHESTRA=1
description = Orchestra-n12
group1 = Orchestra
group2 = 12 nodes


[layered-n15]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=15
makeflags = LAYERED=1
description = Layered-n15
group1 = Layered
group2 = 15 nodes

[minimal-n15]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=15 -DTSCH_SCHEDULE_CONF_WITH_6TISCH_MINIMAL=1
description = 6TiSCH-minimal-n15
group1 = Minimal
group2 = 15 nodes

[orchestra-n15]
cflagsextra = -DSEND_CONF_INTERVAL=200 -DAPP_CONF_NUM_SOURCES=15
makeflags = ORCHESTRA=1
description = Orchestra-n15
group1 = Orchestra
group2 = 15 nodes
