[global]
num_runs = 30

# If this is a test of spatial use (impacts stats only)
spatial_comparison = True

[testbed]
# Duration in minutes
duration = 20

# Duration before applying stats to app packets (only used in stats)
app_warmup = 12

# Nodes utilized
#nodes = 69+67+65+63+61+58+56+54+52+49+46+44+42+40+38+36
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326
#nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316
nodes = 358+356+354+351+348+346+344+342+340+338+336+334+332+330+328+326+324+322+320+318+316+314+312+310+308

[no_spatial_reuse]
cflagsextra = -DSEND_CONF_INTERVAL=207 -DTEST_NO_SPATIAL_REUSE=1
makeflags = LAYERED=1
description = Without spatial reuse

[spatial_reuse]
cflagsextra = -DSEND_CONF_INTERVAL=207
makeflags = LAYERED=1
description = With spatial reuse
has_spatial = True

[simulation]
csc_baseline = linear-baseline.csc

# simulations not supported
#commands = make node.cooja CFLAGSEXTRA=-DSEND_CONF_INTERVAL=1010 TARGET=cooja
